# Generated by Django 4.1.7 on 2023-05-31 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postimage',
            new_name='image',
        ),
    ]
